- .github/workflows/ci.yml
- README.md
- package.json
Basics: install, lint, formatting, and type check
> Add CI workflows

- packages/data-sources/common/package.json
- packages/data-sources/common/src/index.ts
- packages/data-sources/common/tsconfig.json
- packages/data-sources/snowflake/package.json
- packages/data-sources/snowflake/src/index.ts
- packages/data-sources/snowflake/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
> Data sources scaffolding

- packages/database/prisma/migrations/20250724192359_data_source_credentials_columns/migration.sql
- packages/database/prisma/schema.prisma
Adds `type` and `credentials`.
> More DataSourceCredential columns

- packages/data-sources/credentials/package.json
- packages/data-sources/credentials/src/create-data-source-credentials.ts
- packages/data-sources/credentials/src/get-data-source-credentials-list.ts
- packages/data-sources/credentials/src/index.ts
- packages/data-sources/credentials/src/types.ts
- packages/data-sources/credentials/src/update-data-source-credentials.ts
- packages/data-sources/credentials/tsconfig.json
- pnpm-lock.yaml
To manage CRUD on data source credentials.
> Data source credentials package

- packages/core/src/context-model/column-metadata.ts
- packages/data-sources/bigquery/src/bigquery-datasource.ts
- packages/data-sources/common/src/data-source.ts
- packages/data-sources/common/src/index.ts
- packages/data-sources/snowflake/src/snowflake-datasource.ts
A function to get a list of columns from a data source.
Implementing it for Snowflake.
> Get columns list

- .env
- .gitignore
- Dockerfile.migrate
- Dockerfile.web
- docker-compose.yml
`docker-compose up` will pull from there.
> Have .env in root for quick start

- Dockerfile.mcp-server
- Dockerfile.web
- docker-compose.yml
Make all the ports controlled by the env vars in docker.
> Pass through docker ports

- packages/core/src/context-model/column-metadata.ts
- packages/core/src/context-model/table-metadata.ts
- packages/core/src/index.ts
- packages/data-sources/bigquery/src/bigquery-datasource.ts
- packages/data-sources/common/src/data-source.ts
- packages/data-sources/snowflake/src/snowflake-datasource.ts
SystemMetadata -> Definition to be more standard.
> Renaming core types

- docs/auth.md
Proposal for auth for the open source ContextHub.
Implementation:
https://github.com/contexthubhq/contexthub/pull/31
> Auth proposal

- apps/mcp-server/package.json
- apps/mcp-server/src/mcp/tools/register-list-data-sources.ts
- apps/mcp-server/src/mcp/tools/register-list-tables.ts
- apps/mcp-server/src/mcp/tools/register-tools.ts
- packages/data-sources/credentials/src/get-data-source-credentials-list.ts
- packages/data-sources/credentials/src/get-data-source-credentials.ts
- packages/data-sources/credentials/src/index.ts
- pnpm-lock.yaml
- Adds a `list-data-sources` tool to list all available data sources.
- Adds a `dataSourceId` param to the `list-tables` tool so that we only return tables from one data source.
> Support multiple data sources

- packages/context-sources/package.json
- packages/context-sources/src/context-source.ts
- packages/context-sources/src/in-memory-text-input-context-source.ts
- packages/context-sources/src/index.ts
- packages/context-sources/tsconfig.json
- packages/core/package.json
- packages/data-sources/snowflake/package.json
- pnpm-lock.yaml
- Created package.json and tsconfig.json for context-sources.
- Implemented ContextSource interface and InMemoryTextInputContextSource class.
- Added index file to export main interface and implementation.
- Updated dependencies to use specific version of zod (3.25.66) across related packages.
> Add context sources package with initial implementation

- packages/context-engine/package.json
- packages/context-engine/src/context-engine.ts
- packages/context-engine/src/index.ts
- packages/context-engine/src/openai-agent-context-engine.ts
- packages/context-engine/src/test-openai-agent-context-engine.ts
- packages/context-engine/src/types.ts
- packages/context-engine/tsconfig.json
- packages/context-sources/src/in-memory-text-input-context-source.ts
- pnpm-lock.yaml
- Introduced the `@contexthub/context-engine` package for generating table and column context.
- Added `package.json` and `tsconfig.json` for package configuration.
- Implemented the `ContextEngine` interface and `OpenAIAgentContextEngine` class for context generation using OpenAI agents.
- Created types for context generation inputs and results in `types.ts`.
- Developed a test script to validate the context engine functionality with in-memory context sources.
> Add context engine package with OpenAI implementation

- apps/mcp-server/src/mcp/tools/register-list-data-sources.ts
- apps/web/src/app/data-sources/connect-data-source-button.tsx
- apps/web/src/app/data-sources/connect-data-source.ts
- apps/web/src/app/data-sources/get-data-source-connections.ts
- apps/web/src/app/data-sources/page.tsx
- apps/web/src/types/connect-data-source-form.ts
- packages/data-sources/connections/src/create-data-source-connection.ts
- packages/data-sources/connections/src/get-data-source-connection.ts
- packages/data-sources/connections/src/get-data-source-connections-list.ts
- packages/data-sources/connections/src/types.ts
- packages/data-sources/connections/src/update-data-source-connection.ts
- packages/database/prisma/migrations/20250801215236_data_source_name/migration.sql
- packages/database/prisma/schema.prisma
> Add data source name

- apps/web/package.json
- apps/web/src/app/data-sources/data-source-display.tsx
- apps/web/src/app/data-sources/page.tsx
- apps/web/src/components/ui/select.tsx
- pnpm-lock.yaml
> Data source display

- apps/web/package.json
- apps/web/src/app/layout.tsx
- apps/web/src/app/react-query-provider.tsx
- pnpm-lock.yaml
Adds the React Query library so it can be used to dynamically fetch data.
> Add react query

- apps/web/src/app/data-sources/connect-data-source.ts
> Revalidate data sources

- apps/web/package.json
- apps/web/src/app/data-sources/connect-data-source-button.tsx
- apps/web/src/app/data-sources/connection-form.tsx
- apps/web/src/app/layout.tsx
- apps/web/src/components/ui/sonner.tsx
- pnpm-lock.yaml
- Add a toast on successful connection
- Separate form out to its own component
> Data source form improvements

- apps/web/src/api/use-table-details-query.ts
- apps/web/src/app/api/tables/[dataSourceConnectionId]/[fullyQualifiedTableName]/route.ts
- apps/web/src/app/context/tables-and-columns/edit-context.tsx
- apps/web/src/app/context/tables-and-columns/edit-table.tsx
- apps/web/src/components/ui/table.tsx
- apps/web/src/types/table-details-query-result.ts
> More context view

- apps/web/package.json
- apps/web/src/app/context/tables-and-columns/edit-table.tsx
- apps/web/src/components/ui/popover.tsx
- apps/web/src/components/ui/textarea.tsx
- pnpm-lock.yaml
Persisting on server not implemented yet.
> Client side column editing functionality

- apps/web/src/app/context/tables-and-columns/page.tsx
- apps/web/src/app/data-sources/page.tsx
To not break build while building without env vars.
> Force dynamic

- apps/web/src/app/context/metrics/metrics-table.tsx
- apps/web/src/app/context/metrics/page.tsx
- apps/web/src/components/layout/app-sidebar.tsx
- apps/web/src/components/ui/typography.tsx
- packages/core/src/index.ts
> Add metrics page

- apps/web/package.json
- apps/web/src/app/data-sources/connect-data-source-button.tsx
- apps/web/src/app/data-sources/page-client.tsx
- apps/web/src/app/data-sources/page.tsx
- apps/web/src/components/ui/command.tsx
- pnpm-lock.yaml
> Better looking data source select with search

- apps/mcp-server/package.json
- packages/context-engine/package.json
- packages/context-sources/package.json
- packages/core/package.json
- packages/data-sources/all/package.json
- packages/data-sources/common/package.json
- packages/data-sources/connections/package.json
- packages/data-sources/snowflake/package.json
- packages/database/package.json
> Fix check-types

- packages/database/prisma/migrations/20250810184543_initialize_context_repository/migration.sql
> Initialize context repo

- apps/web/package.json
- apps/web/src/app/api/tables/[dataSourceConnectionId]/[fullyQualifiedTableName]/route.ts
- apps/web/src/lib/get-context-repository.ts
- packages/context-repository/src/database-context-repository.ts
- packages/context-repository/src/in-memory-context-working-copy.ts
- pnpm-lock.yaml
Reads table and column context from repo in web app.
> Read from repo in web app

- apps/web/src/api/use-upsert-table-context-mutation.ts
- apps/web/src/app/api/context/table/route.ts
- apps/web/src/app/api/tables/[dataSourceConnectionId]/[fullyQualifiedTableName]/route.ts
- apps/web/src/app/context/tables-and-columns/table-edit-section.tsx
- apps/web/src/types/table-details-query-result.ts
Persists the updating of table context.
> Update table context

- apps/web/src/api/query-keys.ts
- apps/web/src/api/use-create-metric-mutation.ts
- apps/web/src/api/use-metrics-query.ts
- apps/web/src/api/use-update-metric-mutation.ts
- apps/web/src/app/api/context/metric/route.ts
- apps/web/src/app/context/metrics/add-metric-button.tsx
- apps/web/src/app/context/metrics/metric-sheet.tsx
- apps/web/src/app/context/metrics/metrics-table.tsx
- apps/web/src/app/context/metrics/page.tsx
Persist the metrics in the repository
> Create and update metric

- apps/mcp-server/src/mcp/tools/register-execute-query.ts
- apps/mcp-server/src/mcp/tools/register-list-columns.ts
- apps/mcp-server/src/mcp/tools/register-list-data-source-connections.ts
- apps/mcp-server/src/mcp/tools/register-list-tables.ts
- apps/mcp-server/src/mcp/tools/register-tools.ts
Also rename data sources to data source connections to be more accurate.
> Column context in MCP

- packages/context-repository/package.json
- packages/context-repository/src/database-context-repository.test.ts
- packages/context-repository/src/database-context-repository.ts
- packages/database/src/index.ts
- packages/test-database/package.json
- packages/test-database/src/container.ts
- packages/test-database/src/context.ts
- packages/test-database/src/index.ts
- packages/test-database/src/reset.ts
- packages/test-database/tsconfig.json
- pnpm-lock.yaml
There's some complex stateful code being written such as the context repository and the jobs, so adding database tests.
> Testcontainers database tests

- packages/database/prisma/migrations/20250814141626_jobs/migration.sql
- packages/database/prisma/schema.prisma
A simple job queue in Postgres.
> Jobs in the database

- packages/test-database/package.json
- packages/test-database/src/container.ts
- pnpm-lock.yaml
Use more built in functionality.
> Simplify test container use

- packages/job-queue/src/index.ts
- packages/job-queue/src/queue.ts
- packages/job-queue/src/types.ts
For showing the queued / failed jobs to the user
> listJobs function

- apps/mcp-server/src/mcp/tools/register-list-columns.ts
- apps/mcp-server/src/mcp/tools/register-list-concepts.ts
- apps/mcp-server/src/mcp/tools/register-list-metrics.ts
- apps/mcp-server/src/mcp/tools/register-list-tables.ts
- apps/web/src/app/api/agent-jobs/[jobId]/route.ts
- apps/web/src/app/api/agent-jobs/route.ts
- apps/web/src/app/api/context/column/route.ts
- apps/web/src/app/api/context/concept/route.ts
- apps/web/src/app/api/context/metric/route.ts
- apps/web/src/app/api/context/table/route.ts
- apps/web/src/app/api/tables/[dataSourceConnectionId]/[fullyQualifiedTableName]/route.ts
- apps/worker/src/handle-context-agent-job.ts
- apps/worker/src/run-worker.ts
- packages/context-agent/src/merge-context-agent-result.ts
- packages/context-agent/src/run.ts
- packages/context-repository/package.json
- packages/context-repository/src/index.ts
- packages/context-repository/src/server.ts
- packages/job-queue/package.json
- packages/job-queue/src/index.ts
- packages/job-queue/src/queue.test.ts
- packages/job-queue/src/server.ts
...to keep server-only code leaking to the front-end.
> Make separate server exports
